apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: java-demo
spec:
  ingressClassName: nginx
  rules:
  - host: yunlang.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: java-demo
            port:
              number: 80