apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
spec:
  replicas: 3
  selector:
    matchLabels:
      project: test
      app: test-app
  template:
    metadata:
      labels:
        project: test
        app: test-app
    spec:
      imagePullSecrets: 
      - name: "docker-regsitry-auth"
      containers:
      - name: test-app
        image: harbor.cn/library/busybox:1.0.0        
        args:
        - /bin/sh
        - -c
        - sleep 10; touch /tmp/healthy; sleep 30000
        readinessProbe:           #就绪探针
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 10         #10s之后开始第一次探测
          periodSeconds: 5                #第一次探测之后每隔5s探测一次